"""Propose per-sector rainfall thresholds from historical daily rainfall (WP7, Section 9.2).

Reads one historical daily-rainfall CSV per sector, computes rolling 7-day totals,
and proposes the dry and wet thresholds as configurable percentiles of those totals
(default: 20th and 80th). A report is always written to
``docs/calibration/rainfall-thresholds.md``; rows are only saved to the
``advisory_thresholds`` table with --apply, each recording its source CSV.

CSV format (header required): a ``date`` column (YYYY-MM-DD) and an ``mm`` column
(rainfall in millimetres; ``rainfall_mm``/``value`` are also accepted).

    python scripts/calibrate_rainfall_thresholds.py \\
        --input "Ngeruka=data/rainfall/neruka.csv" \\
        --input "Mareba=data/rainfall/mareba.csv" \\
        --apply

Exit codes: 0 = every sector proposed (applied or not), 1 = at least one sector failed.
"""
import argparse
import csv
import sys
from datetime import date, datetime, timedelta
from math import floor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # make the `app` package importable

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import AdvisoryThreshold, Sector
from app.db.session import SessionLocal

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REPORT = PROJECT_ROOT / "docs" / "calibration" / "rainfall-thresholds.md"
DATE_KEYS = ("date", "day", "timestamp")
MM_KEYS = ("mm", "rainfall_mm", "value", "rain")


def load_daily(path: Path) -> list[tuple[date, float]]:
    """Daily rainfall rows sorted by date; duplicate dates are summed."""
    with path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError(f"{path.name}: the CSV has no header row")
        headers = {name.strip().lower(): name for name in reader.fieldnames}
        date_key = next((headers[key] for key in DATE_KEYS if key in headers), None)
        mm_key = next((headers[key] for key in MM_KEYS if key in headers), None)
        if date_key is None or mm_key is None:
            raise ValueError(f"{path.name}: needs a date column ({', '.join(DATE_KEYS)}) and an mm column ({', '.join(MM_KEYS)})")
        totals: dict[date, float] = {}
        for number, row in enumerate(reader, start=2):
            raw_date, raw_mm = (row.get(date_key) or "").strip(), (row.get(mm_key) or "").strip()
            if not raw_date and not raw_mm:
                continue  # blank line
            try:
                day = datetime.strptime(raw_date[:10], "%Y-%m-%d").date()
                mm = float(raw_mm.replace(",", "."))
            except ValueError as error:
                raise ValueError(f"{path.name} row {number}: {error}") from error
            totals[day] = totals.get(day, 0.0) + mm
    return sorted(totals.items())


def rolling_7day(daily: list[tuple[date, float]]) -> list[float]:
    """Rolling 7-day totals for every date with all 7 consecutive days present."""
    by_day = dict(daily)
    totals = []
    for day, _ in daily:
        window = [by_day.get(day - timedelta(days=offset)) for offset in range(7)]
        if all(value is not None for value in window):
            totals.append(round(sum(window), 1))
    return totals


def percentile(values: list[float], p: float) -> float:
    """Linear-interpolated percentile (no third-party dependency)."""
    ordered = sorted(values)
    if not ordered:
        raise ValueError("no values")
    if len(ordered) == 1:
        return ordered[0]
    rank = (len(ordered) - 1) * (p / 100)
    low, high = floor(rank), min(floor(rank) + 1, len(ordered) - 1)
    return ordered[low] + (ordered[high] - ordered[low]) * (rank - low)


def propose(totals: list[float], dry_percentile: float, wet_percentile: float) -> tuple[float, float]:
    dry = round(percentile(totals, dry_percentile), 1)
    wet = round(percentile(totals, wet_percentile), 1)
    if wet <= dry:
        raise ValueError(f"wet threshold ({wet}) must be above the dry threshold ({dry}); check the data or the percentiles")
    return dry, wet


def build_report(proposals: list[dict], dry_percentile: float, wet_percentile: float, applied: bool) -> str:
    """Markdown report: one section per sector with source, coverage and proposal."""
    lines = [
        "# Rainfall threshold calibration",
        "",
        f"Generated by `scripts/calibrate_rainfall_thresholds.py` on {date.today().isoformat()}.",
        "",
        f"Rolling 7-day rainfall totals per sector; the dry threshold is the **{dry_percentile:g}th percentile**",
        f"and the wet threshold the **{wet_percentile:g}th percentile** of those totals.",
        "",
        "> Percentiles suggest values from history. District staff must confirm them against",
        "> local knowledge before the pilot; every row records the CSV it came from.",
        "",
    ]
    for proposal in proposals:
        lines += [
            f"## {proposal['sector']}",
            "",
            f"- Source: `{proposal['source']}`",
            f"- Coverage: {proposal['days']} days ({proposal['first']} to {proposal['last']}), {proposal['windows']} complete 7-day windows",
            f"- Proposed: dry **{proposal['dry_mm']} mm**, wet **{proposal['wet_mm']} mm** (7-day totals)",
            f"- Previously configured: {proposal['previous']}",
            "",
        ]
    lines += ["", f"Status: {'**applied** to `advisory_thresholds`' if applied else '**proposed only** — re-run with `--apply` to save'}.", ""]
    return "\n".join(lines)


def _parse_input(spec: str, fallback_sector: str | None) -> tuple[str, Path]:
    sector, separator, raw_path = spec.partition("=")
    if not separator:
        if not fallback_sector:
            raise ValueError(f"--input {spec}: use SECTOR=PATH (or pass a single --sector)")
        return fallback_sector, Path(sector)
    return sector.strip(), Path(raw_path.strip())


def run(db: Session, inputs: list[tuple[str, Path]], dry_percentile: float, wet_percentile: float,
        report_path: Path, apply: bool) -> int:
    sectors = {sector.name.lower(): sector for sector in db.scalars(select(Sector))}
    thresholds = {row.sector_id: row for row in db.scalars(select(AdvisoryThreshold))}
    proposals: list[dict] = []
    errors: list[str] = []
    for sector_name, path in inputs:
        if not path.is_file():
            errors.append(f"{sector_name}: file not found: {path}")
            continue
        sector = sectors.get(sector_name.lower())
        if sector is None:
            known = ", ".join(sorted(name.title() for name in sectors)) or "no sectors loaded"
            errors.append(f"{sector_name}: no sector with this name (known: {known})")
            continue
        try:
            daily = load_daily(path)
            totals = rolling_7day(daily)
            dry, wet = propose(totals, dry_percentile, wet_percentile)
        except ValueError as error:
            errors.append(f"{sector_name}: {error}")
            continue
        existing = thresholds.get(sector.id)
        previous = (f"{existing.dry_mm} / {existing.wet_mm} mm from {existing.source}" if existing
                    else "environment defaults (DRY_SPELL_THRESHOLD_MM / WET_SPELL_THRESHOLD_MM)")
        proposals.append({
            "sector_id": sector.id, "sector": sector.name, "source": str(path),
            "days": len(daily), "first": daily[0][0].isoformat(), "last": daily[-1][0].isoformat(),
            "windows": len(totals), "dry_mm": dry, "wet_mm": wet, "previous": previous,
        })

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(build_report(proposals, dry_percentile, wet_percentile, apply and not errors), encoding="utf-8")
    print(f"Report written to {report_path}")

    for proposal in proposals:
        print(f"  {proposal['sector']}: dry < {proposal['dry_mm']} mm, wet > {proposal['wet_mm']} mm "
              f"({proposal['windows']} windows from {proposal['source']})")
    for message in errors:
        print(f"FAILED {message}")

    if apply and not errors and proposals:
        today = date.today()
        for proposal in proposals:
            existing = thresholds.get(proposal["sector_id"])
            if existing:
                existing.dry_mm, existing.wet_mm = proposal["dry_mm"], proposal["wet_mm"]
                existing.source, existing.valid_from = proposal["source"], today
            else:
                db.add(AdvisoryThreshold(sector_id=proposal["sector_id"], dry_mm=proposal["dry_mm"],
                                         wet_mm=proposal["wet_mm"], source=proposal["source"], valid_from=today))
        db.commit()
        print(f"Applied thresholds for {len(proposals)} sector(s).")
    elif apply:
        print("Nothing applied: fix the failures above and re-run.")
    elif proposals:
        print("Proposed only. Re-run with --apply to save these values.")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", action="append", default=[], metavar="SECTOR=PATH",
                        help="daily rainfall CSV for one sector (repeatable)")
    parser.add_argument("--sector", help="sector name when a single --input is a plain path")
    parser.add_argument("--dry-percentile", type=float, default=20)
    parser.add_argument("--wet-percentile", type=float, default=80)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--apply", action="store_true", help="save to advisory_thresholds (default: report only)")
    args = parser.parse_args(argv)
    if not args.input:
        parser.error("at least one --input SECTOR=PATH is required")

    try:
        inputs = [_parse_input(spec, args.sector) for spec in args.input]
    except ValueError as error:
        parser.error(str(error))
        return 1  # pragma: no cover

    db = SessionLocal()
    try:
        return run(db, inputs, args.dry_percentile, args.wet_percentile, args.report, args.apply)
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(main())
